### ISSUE TITLE
Support running as non-root

### ISSUE THREAD

**Issue by focusaurus** [guangie88/rustfmt-clippy#12]
I tried running this image as a non-root user and got an fs permission denied error trying to run `cargo clippy`:

```
/opt/.cargo/bin/cargo clippy
error: failed to open: /opt/.cargo/registry/index/github.com-1ecc6299db9ec823/.cargo-index-lock

Caused by:
  Permission denied (os error 13)
```

Would you be willing to adjust filesystem permissions so `docker run --user=$(id -u)` would work?

**Comment by guangie88** [comment]
Let me check what can be done, should be able to implement this.

**Comment by guangie88** [comment]
Think I have fixed the problem for non-root user, check out the latest instruction:
https://github.com/guangie88/rustfmt-clippy#how-to-use. Note that it uses `stable` toolchain in the command.

The currently the official `nightly` toolchain doesn't have any valid builds with `clippy`, if you need to use nightly toolchain, then have to wait for some time until there's one valid build to generate a new nightly image.

Let me know if this works out for you too.

**Comment by focusaurus** [comment]
Seems to work. Thanks!
